import { defineConfig } from 'eslint/config'
import prettier from 'eslint-plugin-prettier'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import js from '@eslint/js'
import { FlatCompat } from '@eslint/eslintrc'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const compat = new FlatCompat({
  baseDirectory: __dirname,
  recommendedConfig: js.configs.recommended,
  allConfig: js.configs.all,
})

export default defineConfig([
  {
    extends: compat.extends('prettier'),

    plugins: {
      prettier,
    },

    languageOptions: {
      globals: {
        __command: false,
        NSApplication: false,
        NSApp: false,
        NSMakeRect: false,
        NSScreen: false,
        NSColor: false,
        NSClosableWindowMask: false,
        NSFullScreenWindowMask: false,
        NSWindowZoomButton: false,
        NSFloatingWindowLevel: false,
        NSMakeSize: false,
        NSHeight: false,
        NSMiniaturizableWindowMask: false,
        NSWindowCollectionBehaviorFullScreenPrimary: false,
        NSVisualEffectView: false,
        NSWindowCollectionBehaviorFullScreenAuxiliary: false,
        NSNormalWindowLevel: false,
        NSVisualEffectBlendingModeBehindWindow: false,
        CGWindowLevelForKey: false,
        kCGMaximumWindowLevelKey: false,
        kCGMinimumWindowLevelKey: false,
        NSTornOffMenuWindowLevel: false,
        NSModalPanelWindowLevel: false,
        NSMainMenuWindowLevel: false,
        NSResizableWindowMask: false,
        NSStatusWindowLevel: false,
        NSPopUpMenuWindowLevel: false,
        NSScreenSaverWindowLevel: false,
        NSDockWindowLevel: false,
        NSInformationalRequest: false,
        NSWindowCollectionBehaviorCanJoinAllSpaces: false,
        NSWindowSharingNone: false,
        NSWindowSharingReadOnly: false,
        NSViewWidthSizable: false,
        NSViewHeightSizable: false,
        NSVisualEffectStateActive: false,
        NSWindowBelow: false,
        NSVisualEffectMaterialLight: false,
        NSVisualEffectMaterialAppearanceBased: false,
        NSVisualEffectMaterialDark: false,
        NSVisualEffectMaterialTitlebar: false,
        NSVisualEffectMaterialSelection: false,
        NSVisualEffectMaterialMenu: false,
        NSVisualEffectMaterialPopover: false,
        NSVisualEffectMaterialSidebar: false,
        NSVisualEffectMaterialMediumLight: false,
        NSVisualEffectMaterialUltraDark: false,
        NSWindowAbove: false,
        NSDictionary: false,
        NSKeyValueObservingOptionNew: false,
        NSLayoutConstraint: false,
        NSLayoutRelationEqual: false,
        NSLayoutAttributeLeft: false,
        NSLayoutAttributeTop: false,
        NSLayoutAttributeRight: false,
        NSLayoutAttributeBottom: false,
        NSUUID: false,
        NSThread: false,
        coscript: false,
        NSWidth: false,
        NSTitledWindowMask: false,
        NSTexturedBackgroundWindowMask: false,
        NSPanel: false,
        NSBackingStoreBuffered: false,
        WKWebView: false,
        kCGDesktopWindowLevel: false,
        NSWindowCollectionBehaviorStationary: false,
        NSWindowCollectionBehaviorIgnoresCycle: false,
        NSWindowTitleHidden: false,
        NSToolbar: false,
        NSWindowFullScreenButton: false,
        NSWindowMiniaturizeButton: false,
        NSWindowCloseButton: false,
        NSEventTypeLeftMouseDown: false,
        NSMutableDictionary: false,
        arguments: false,
        window: false,
        NSFullSizeContentViewWindowMask: false,
        CGRectMake: false,
        WKWebViewConfiguration: false,
        NSURLRequest: false,
        NSURL: false,
        __mocha__: false,
        CGPointMake: false,
        WKUserScript: false,
        NSURLCredential: false,
        CGSizeMake: false,
        NSEvent: false,
        WKInspectorWKWebView: false,
        NSString: false,
        NSCharacterSet: false,
        MSTheme: false,
        NSKeyValueChangeNewKey: false,
      },
    },

    rules: {
      'prefer-rest-params': 'off',
      'prefer-arrow-callback': 'off',
      'no-var': 'off',
      'vars-on-top': 'off',
      'func-names': 'off',
      'no-param-reassign': 'off',
      'no-bitwise': 'off',
      'prefer-destructuring': 'off',
      'object-shorthand': 'off',
      'prefer-template': 'off',
      'no-underscore-dangle': 'off',
      'class-methods-use-this': 'warn',
      'no-useless-constructor': 'warn',
      eqeqeq: 'off',
      strict: 'off',
      'prefer-spread': 'off',

      'prettier/prettier': [
        'error',
        {
          singleQuote: true,
          trailingComma: 'es5',
          semi: false,
          parser: 'typescript',
        },
      ],
    },
  },
])
